server:
  http_listen_port: 9080

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: static
    static_configs:
      - targets:
          - localhost
        labels:
          job: logs
          __path__: /var/log/containers/*hotrod*.log
          container: hotrod
      - targets:
          - localhost
        labels:
          job: logs
          __path__: /var/log/containers/*log-generator*.log
          container: log-generator
